//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tarjetas_asp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.tarjetaSoap")]
    public interface tarjetaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        tarjetas_asp.ServiceReference1.HelloWorldResponse HelloWorld(tarjetas_asp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.HelloWorldResponse> HelloWorldAsync(tarjetas_asp.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento soapRequest del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreditCardInfo", ReplyAction="*")]
        tarjetas_asp.ServiceReference1.CreditCardInfoResponse CreditCardInfo(tarjetas_asp.ServiceReference1.CreditCardInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreditCardInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.CreditCardInfoResponse> CreditCardInfoAsync(tarjetas_asp.ServiceReference1.CreditCardInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessCreditCard", ReplyAction="*")]
        tarjetas_asp.ServiceReference1.ProcessCreditCardResponse ProcessCreditCard(tarjetas_asp.ServiceReference1.ProcessCreditCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessCreditCard", ReplyAction="*")]
        System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.ProcessCreditCardResponse> ProcessCreditCardAsync(tarjetas_asp.ServiceReference1.ProcessCreditCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public tarjetas_asp.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(tarjetas_asp.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public tarjetas_asp.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(tarjetas_asp.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditCardInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditCardInfo", Namespace="http://tempuri.org/", Order=0)]
        public tarjetas_asp.ServiceReference1.CreditCardInfoRequestBody Body;
        
        public CreditCardInfoRequest() {
        }
        
        public CreditCardInfoRequest(tarjetas_asp.ServiceReference1.CreditCardInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCardInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement soapRequest;
        
        public CreditCardInfoRequestBody() {
        }
        
        public CreditCardInfoRequestBody(System.Xml.Linq.XElement soapRequest) {
            this.soapRequest = soapRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditCardInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditCardInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public tarjetas_asp.ServiceReference1.CreditCardInfoResponseBody Body;
        
        public CreditCardInfoResponse() {
        }
        
        public CreditCardInfoResponse(tarjetas_asp.ServiceReference1.CreditCardInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCardInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreditCardInfoResult;
        
        public CreditCardInfoResponseBody() {
        }
        
        public CreditCardInfoResponseBody(string CreditCardInfoResult) {
            this.CreditCardInfoResult = CreditCardInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessCreditCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessCreditCard", Namespace="http://tempuri.org/", Order=0)]
        public tarjetas_asp.ServiceReference1.ProcessCreditCardRequestBody Body;
        
        public ProcessCreditCardRequest() {
        }
        
        public ProcessCreditCardRequest(tarjetas_asp.ServiceReference1.ProcessCreditCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessCreditCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xml;
        
        public ProcessCreditCardRequestBody() {
        }
        
        public ProcessCreditCardRequestBody(System.Xml.Linq.XElement xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessCreditCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessCreditCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public tarjetas_asp.ServiceReference1.ProcessCreditCardResponseBody Body;
        
        public ProcessCreditCardResponse() {
        }
        
        public ProcessCreditCardResponse(tarjetas_asp.ServiceReference1.ProcessCreditCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessCreditCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessCreditCardResult;
        
        public ProcessCreditCardResponseBody() {
        }
        
        public ProcessCreditCardResponseBody(string ProcessCreditCardResult) {
            this.ProcessCreditCardResult = ProcessCreditCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface tarjetaSoapChannel : tarjetas_asp.ServiceReference1.tarjetaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class tarjetaSoapClient : System.ServiceModel.ClientBase<tarjetas_asp.ServiceReference1.tarjetaSoap>, tarjetas_asp.ServiceReference1.tarjetaSoap {
        
        public tarjetaSoapClient() {
        }
        
        public tarjetaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public tarjetaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tarjetaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public tarjetaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tarjetas_asp.ServiceReference1.HelloWorldResponse tarjetas_asp.ServiceReference1.tarjetaSoap.HelloWorld(tarjetas_asp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            tarjetas_asp.ServiceReference1.HelloWorldRequest inValue = new tarjetas_asp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new tarjetas_asp.ServiceReference1.HelloWorldRequestBody();
            tarjetas_asp.ServiceReference1.HelloWorldResponse retVal = ((tarjetas_asp.ServiceReference1.tarjetaSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.HelloWorldResponse> tarjetas_asp.ServiceReference1.tarjetaSoap.HelloWorldAsync(tarjetas_asp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            tarjetas_asp.ServiceReference1.HelloWorldRequest inValue = new tarjetas_asp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new tarjetas_asp.ServiceReference1.HelloWorldRequestBody();
            return ((tarjetas_asp.ServiceReference1.tarjetaSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tarjetas_asp.ServiceReference1.CreditCardInfoResponse tarjetas_asp.ServiceReference1.tarjetaSoap.CreditCardInfo(tarjetas_asp.ServiceReference1.CreditCardInfoRequest request) {
            return base.Channel.CreditCardInfo(request);
        }
        
        public string CreditCardInfo(System.Xml.Linq.XElement soapRequest) {
            tarjetas_asp.ServiceReference1.CreditCardInfoRequest inValue = new tarjetas_asp.ServiceReference1.CreditCardInfoRequest();
            inValue.Body = new tarjetas_asp.ServiceReference1.CreditCardInfoRequestBody();
            inValue.Body.soapRequest = soapRequest;
            tarjetas_asp.ServiceReference1.CreditCardInfoResponse retVal = ((tarjetas_asp.ServiceReference1.tarjetaSoap)(this)).CreditCardInfo(inValue);
            return retVal.Body.CreditCardInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.CreditCardInfoResponse> tarjetas_asp.ServiceReference1.tarjetaSoap.CreditCardInfoAsync(tarjetas_asp.ServiceReference1.CreditCardInfoRequest request) {
            return base.Channel.CreditCardInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.CreditCardInfoResponse> CreditCardInfoAsync(System.Xml.Linq.XElement soapRequest) {
            tarjetas_asp.ServiceReference1.CreditCardInfoRequest inValue = new tarjetas_asp.ServiceReference1.CreditCardInfoRequest();
            inValue.Body = new tarjetas_asp.ServiceReference1.CreditCardInfoRequestBody();
            inValue.Body.soapRequest = soapRequest;
            return ((tarjetas_asp.ServiceReference1.tarjetaSoap)(this)).CreditCardInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        tarjetas_asp.ServiceReference1.ProcessCreditCardResponse tarjetas_asp.ServiceReference1.tarjetaSoap.ProcessCreditCard(tarjetas_asp.ServiceReference1.ProcessCreditCardRequest request) {
            return base.Channel.ProcessCreditCard(request);
        }
        
        public string ProcessCreditCard(System.Xml.Linq.XElement xml) {
            tarjetas_asp.ServiceReference1.ProcessCreditCardRequest inValue = new tarjetas_asp.ServiceReference1.ProcessCreditCardRequest();
            inValue.Body = new tarjetas_asp.ServiceReference1.ProcessCreditCardRequestBody();
            inValue.Body.xml = xml;
            tarjetas_asp.ServiceReference1.ProcessCreditCardResponse retVal = ((tarjetas_asp.ServiceReference1.tarjetaSoap)(this)).ProcessCreditCard(inValue);
            return retVal.Body.ProcessCreditCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.ProcessCreditCardResponse> tarjetas_asp.ServiceReference1.tarjetaSoap.ProcessCreditCardAsync(tarjetas_asp.ServiceReference1.ProcessCreditCardRequest request) {
            return base.Channel.ProcessCreditCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<tarjetas_asp.ServiceReference1.ProcessCreditCardResponse> ProcessCreditCardAsync(System.Xml.Linq.XElement xml) {
            tarjetas_asp.ServiceReference1.ProcessCreditCardRequest inValue = new tarjetas_asp.ServiceReference1.ProcessCreditCardRequest();
            inValue.Body = new tarjetas_asp.ServiceReference1.ProcessCreditCardRequestBody();
            inValue.Body.xml = xml;
            return ((tarjetas_asp.ServiceReference1.tarjetaSoap)(this)).ProcessCreditCardAsync(inValue);
        }
    }
}
